name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: "enhancement"
    title:
      - "/^feat(\\(.+\\))?:/i"
  - label: "bug"
    title:
      - "/^fix(\\(.+\\))?:/i"
  - label: "documentation"
    title:
      - "/^docs(\\(.+\\))?:/i"
  - label: "github_actions"
    title:
      - "/^ci(\\(.+\\))?:/i"

categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "📝 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency Updates"
    labels:
      - "dependencies"
  - title: "🧰 Maintenance"
    labels:
      - "github_actions"
      - "accessibility"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

version-resolver:
  minor:
    labels:
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "documentation"
      - "dependencies"
      - "github_actions"
      - "accessibility"
  default: patch
